module.exports = [{
    id: 1,
    title: "Improve Production Line Efficiency",
    description: "Our packaging process at Production Line 2 has encountered efficiency problems recently, resulting in a 10% increase in packaging time. This issue was noticed by the Line Leader during their regular shift inspection. An incident report (ID: 12345) has been filed. We need to investigate and enhance the production line's efficiency to address this problem.",
    severity: 10,
    occurrence: 10,
    detection: 10,
    rpn: 1000,
    request_status: "Open",
    created_by: 1,
    assigned_to: 4,
    kpi_id: 1,
    
  },
  {
    id: 2,
    title: "Optimize Production Line Layout",
    description: "The current production line layout at Production Line 2 is causing inefficiencies, leading to a 7% increase in production time. This issue was observed by the Line Leader during their shift. To improve efficiency, we need to optimize the production line layout, especially at the packaging station.",
    severity: 7,
    occurrence: 7,
    detection: 8,
    rpn: 392,
    request_status: "pending",
    created_by: 1,
    assigned_to: 4,
    kpi_id: 1
  },
  {
    id: 3,
    title: "Evaluate and Optimize Production Processes",
    description: "We've encountered inefficiencies in our production processes, leading to a 3% increase in defects. These issues were noticed during the quality inspection by the Quality Technician. We need to evaluate and optimize our production processes to reduce defects and improve product quality.",
    severity: 3,
    occurrence: 3,
    detection: 5,
    rpn: 45,
    request_status: "open",
    created_by: 1,
    assigned_to: 8,
    kpi_id: 1
    
  },
  {
    id: 4,
    title: "Address Quality Defects in Line 2",
    description: "Our quality control reports show a recent 2% increase in products rejected due to quality issues, especially in the packaging area at Production Line 2. The Quality Technician has reported this problem. We need to investigate and address the root causes of these defects.",
    severity: 2,
    occurrence: 3,
    detection: 4,
    rpn: 24,
    request_status: "open",
    created_by: 1,
    assigned_to: 2,
    kpi_id: 2
  },
  {
    id: 5,
    title: "Reduce Defects through Process Optimization",
    description: "Our quality control reports show a recent 4% increase in products rejected due to quality issues in the packaging area at Production Line 2. The Quality Technician has reported this problem. We need to investigate and address the root causes of these defects.",
    severity: 3,
    occurrence: 4,
    detection: 4,
    rpn: 48,
    request_status: "pending",
    created_by: 1,
    assigned_to: 2,
    kpi_id: 2
  },
  {
    id: 6,
    title: "Investigate Defect Root Causes",
    description: "We've encountered a recent 4% increase in products rejected due to quality issues in the packaging area at Production Line 2. The Quality Technician has reported this problem. We need to investigate and address the root causes of these defects.",
    severity: 4,
    occurrence: 3,
    detection: 5,
    rpn: 60,
    request_status: "open",
    created_by: 1,
    assigned_to: 2,
    kpi_id: 2,
    
  },
  {
    id: 7,
    title: "Machine Repair - Urgent",
    description: "Machine B-7 at Production Line 2 urgently requires repair due to frequent breakdowns. This issue has been affecting production efficiency. The Maintenance Manager reported this problem. We have dispatched the maintenance team to address this issue.",
    severity: 4,
    occurrence: 5,
    detection: 4,
    rpn: 80,
    request_status: "resolved",
    created_by: 1,
    assigned_to: 3,
    kpi_id: 3
  },
  {
    id: 8,
    title: "Investigate Frequent Machine Downtime",
    description: "We've been experiencing frequent machine downtime at Production Line 2, causing disruptions to our production schedule. This issue has been reported by the Maintenance Manager. We need to investigate the causes of this downtime and implement measures to reduce it.",
    severity: 3,
    occurrence: 4,
    detection: 4,
    rpn: 48,
    request_status: "open",
    created_by: 1,
    assigned_to: 3,
    kpi_id: 3
  },
  {
    id: 9,
    title: "Downtime Reduction Strategy - Develop and Implement",
    description: "We've been experiencing frequent machine downtime at Production Line 2, impacting our productivity. This issue has been reported by the Maintenance Manager. We need to develop and implement a comprehensive strategy to reduce machine downtime and ensure uninterrupted production.",
    severity: 2,
    occurrence: 3,
    detection: 5,
    rpn: 30,
    request_status: "pending",
    created_by: 1,
    assigned_to: 3,
    kpi_id: 3
  }
  ]